services:
  - type: web
    name: citizenair-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: NOTION_TOKEN
        sync: false # You'll need to set this manually in Render dashboard
      - key: NOTION_DATABASE_ID
        sync: false # You'll need to set this manually in Render dashboard
      - key: MONGODB_URI
        sync: false # You'll need to set this manually in Render dashboard
